<?php

/**
 * @file
 * Provides functionality for the Commerce Amazon MWS Feed module.
 */

/**
 * Constants.
 */

/**
 * The name of the logger channel to use throughout this module.
 */
const COMMERCE_AMWS_FEED_LOGGER_CHANNEL = 'commerce_amws_feed';

/**
 * Hooks.
 */

/**
 * Implements hook_cron().
 */
function commerce_amws_feed_cron() {
  $feed_service = \Drupal::service('commerce_amws_feed.feed_service');
  $feed_service->updateSubmitted();
  $feed_service->updateProcessed();
}
